var baseCatalog = [
    {
        ObjectName: 'ProgenitorCommander',
        ClassName: 'Commander',
        DisplayName: 'Progenitor',
        UnitSpec: '/pa/units/commanders/imperial_progenitor/imperial_progenitor.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_progenitor.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_progenitor.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_progenitor_thumb.png'
    },
    {
        ObjectName: 'AlphaCommander',
        ClassName: 'Commander',
        DisplayName: 'Alpha',
        UnitSpec: '/pa/units/commanders/imperial_alpha/imperial_alpha.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_alpha.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_alpha.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_alpha_thumb.png'
    },
    {
        ObjectName: 'ThetaCommander',
        ClassName: 'Commander',
        DisplayName: 'Theta',
        UnitSpec: '/pa/units/commanders/imperial_theta/imperial_theta.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_theta.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_theta.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_theta_thumb.png'
    },
    {
        ObjectName: 'DeltaCommander',
        ClassName: 'Commander',
        DisplayName: 'Delta',
        UnitSpec: '/pa/units/commanders/imperial_delta/imperial_delta.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_delta.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_delta.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_delta_thumb.png'
    },
    {
         ObjectName: 'GammaCommander',
         ClassName: 'Commander',
         DisplayName: 'Gamma',
         UnitSpec: '/pa/units/commanders/imperial_gamma/imperial_gamma.json',
         ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_gamma.png',
         ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_gamma.png',
         ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_gamma_thumb.png'
    },
    {
        ObjectName: 'InvictusCommander',
        ClassName: 'Commander',
        DisplayName: 'Invictus',
        UnitSpec: '/pa/units/commanders/imperial_invictus/imperial_invictus.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_invictus.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_invictus.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_invictus_thumb.png'
    },
    {
        ObjectName: 'RaptorCenturion',
        ClassName: 'Commander',
        DisplayName: 'Centurion',
        UnitSpec: '/pa/units/commanders/raptor_centurion/raptor_centurion.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_raptor_centurion.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_raptor_centurion.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_raptor_centurion_thumb.png'
    },
    {
        ObjectName: 'RaptorRallus',
        ClassName: 'Commander',
        DisplayName: 'Rallus',
        UnitSpec: '/pa/units/commanders/raptor_rallus/raptor_rallus.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_raptor_rallus.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_raptor_rallus.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_raptor_rallus_thumb.png'
    },
    {
        ObjectName: 'TankAeson',
        ClassName: 'Commander',
        DisplayName: 'Aeson',
        UnitSpec: '/pa/units/commanders/tank_aeson/tank_aeson.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_tank_aeson.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_tank_aeson.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_tank_aeson_thumb.png'
    },
    {
        ObjectName: 'QuadOsiris',
        ClassName: 'Commander',
        DisplayName: 'Osiris',
        UnitSpec: '/pa/units/commanders/quad_osiris/quad_osiris.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_osiris.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_osiris.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_osiris_thumb.png'
    },
    {
        ObjectName: 'QuadAjax',
        ClassName: 'Commander',
        DisplayName: 'Ajax',
        UnitSpec: '/pa/units/commanders/quad_ajax/quad_ajax.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_ajax.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_ajax.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_ajax_thumb.png'
    },
    {
        ObjectName: 'RaptorNemicus',
        ClassName: 'Commander',
        DisplayName: 'Nemicus',
        UnitSpec: '/pa/units/commanders/raptor_nemicus/raptor_nemicus.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_raptor_nemicus.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_raptor_nemicus.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_raptor_nemicus_thumb.png'
    },
    {
        ObjectName: 'RaptorBeast',
        ClassName: 'Commander',
        DisplayName: 'Beast',
        UnitSpec: '/pa/units/commanders/raptor_beast/raptor_beast.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_raptor_beast.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_raptor_beast.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_raptor_beast_thumb.png',
    },
    {
        ObjectName: 'QuadCalyx',
        ClassName: 'Commander',
        DisplayName: 'Calyx',
        UnitSpec: '/pa/units/commanders/quad_calyx/quad_calyx.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_calyx.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_calyx.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_calyx_thumb.png',
    },
    {
        ObjectName: 'QuadSpiderOfMean',
        ClassName: 'Commander',
        DisplayName: 'Xenosentry',
        UnitSpec: '/pa/units/commanders/quad_spiderofmean/quad_spiderofmean.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_spiderofmean.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_spiderofmean.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_spiderofmean_thumb.png',
        KSBacker: 'Warren Hunt',
        OrigPrice:'$15.00'
    },
    {
        ObjectName: 'QuadXenosentryPrime',
        ClassName: 'Commander',
        DisplayName: 'XenosentryPrime',
        UnitSpec: '/pa/units/commanders/quad_spiderofmean/quad_xenosentryprime.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_spiderofmean.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_spiderofmean.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_spiderofmean_thumb.png',
        KSBacker: 'Warren Hunt',
    },
    {
        ObjectName: 'ImperialAryst0krat',
        ClassName: 'Commander',
        DisplayName: 'Aryst0krat',
        UnitSpec: '/pa/units/commanders/imperial_aryst0krat/imperial_aryst0krat.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_aryst0krat.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_aryst0krat.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_aryst0krat_thumb.png',
        KSBacker: 'Chris McIntyre',
        OrigPrice: '$10.00'
    },
    {
        ObjectName: 'QuadShadowdaemon',
        ClassName: 'Commander',
        DisplayName: 'ShadowDaemon',
        UnitSpec: '/pa/units/commanders/quad_shadowdaemon/quad_shadowdaemon.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_shadowdaemon.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_shadowdaemon.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_shadowdaemon_thumb.png',
        KSBacker: 'David Cartes',
        OrigPrice: '$10.00'
    },
    {
        ObjectName: 'QuadArmalisk',
        ClassName: 'Commander',
        DisplayName: 'Armalisk',
        UnitSpec: '/pa/units/commanders/quad_armalisk/quad_armalisk.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_armalisk.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_armalisk.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_armalisk_thumb.png',
        KSBacker: 'SacrificialLamb',
    },
    {
        ObjectName: 'QuadSacrificialLamb',
        ClassName: 'Commander',
        DisplayName: 'SacrificialLamb',
        UnitSpec: '/pa/units/commanders/quad_sacrificiallamb/quad_sacrificiallamb.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_sacrificiallamb.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_sacrificiallamb.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_sacrificiallamb_thumb.png',
    },
    {
        ObjectName: 'QuadXinthar',
        ClassName: 'Commander',
        DisplayName: 'Xinthar',
        UnitSpec: '/pa/units/commanders/quad_xinthar/quad_xinthar.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_xinthar.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_xinthar.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_xinthar_thumb.png',
        KSBacker: '',
        OrigPrice: '$10.00'
    },
    {
        ObjectName: 'RaptorBetadyne',
        ClassName: 'Commander',
        DisplayName: 'Betadyne',
        UnitSpec: '/pa/units/commanders/raptor_betadyne/raptor_betadyne.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_raptor_betadyne.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_raptor_betadyne.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_raptor_betadyne_thumb.png',
        KSBacker: 'Ron Pepper',
        OrigPrice: '$10.00'
    },
    {
        ObjectName: 'QuadGambitdfa',
        ClassName: 'Commander',
        DisplayName: 'Gambitdfa',
        UnitSpec: '/pa/units/commanders/quad_gambitdfa/quad_gambitdfa.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_gambitdfa.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_gambitdfa.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_gambitdfa_thumb.png',
        KSBacker: 'Michael Mallette',
        OrigPrice: '$10.00'
    },
    {
        ObjectName: 'ImperialAble',
        ClassName: 'Commander',
        DisplayName: 'Able',
        UnitSpec: '/pa/units/commanders/imperial_able/imperial_able.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_able.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_able.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_able_thumb.png',
        OrigPrice: '$10.00'
    },
    {
        ObjectName: 'ImperialKapowaz',
        ClassName: 'Commander',
        DisplayName: 'Kapowaz',
        UnitSpec: '/pa/units/commanders/imperial_kapowaz/imperial_kapowaz.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_kapowaz.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_kapowaz.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_kapowaz_thumb.png',
    },
    {
        ObjectName: 'ImperialChronoblip',
        ClassName: 'Commander',
        DisplayName: 'Chronoblip',
        UnitSpec: '/pa/units/commanders/imperial_chronoblip/imperial_chronoblip.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_chronoblip.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_chronoblip.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_chronoblip_thumb.png',
        KSBacker: 'Nate "chronoblip" Mircovich',
    },
    {
        ObjectName: 'ImperialGnugfur',
        ClassName: 'Commander',
        DisplayName: 'Gnugfur',
        UnitSpec: '/pa/units/commanders/imperial_gnugfur/imperial_gnugfur.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_gnugfur.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_gnugfur.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_gnugfur_thumb.png',
        KSBacker: 'Robert Krondorfer',
    },
    {
        ObjectName: 'QuadTwoboots',
        ClassName: 'Commander',
        DisplayName: 'Twoboots',
        UnitSpec: '/pa/units/commanders/quad_twoboots/quad_twoboots.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_twoboots.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_twoboots.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_twoboots_thumb.png',
        KSBacker: 'twoBoots',
    },
    {
        ObjectName: 'RaptorIwmiked',
        ClassName: 'Commander',
        DisplayName: 'Iwmiked',
        UnitSpec: '/pa/units/commanders/raptor_iwmiked/raptor_iwmiked.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_raptor_iwmiked.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_raptor_iwmiked.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_raptor_iwmiked_thumb.png',
    },
    {
        ObjectName: 'ImperialSangudo',
        ClassName: 'Commander',
        DisplayName: 'Sangudo',
        UnitSpec: '/pa/units/commanders/imperial_sangudo/imperial_sangudo.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_sangudo.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_sangudo.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_sangudo_thumb.png',
        KSBacker: 'Colton Cross',
    },
    {
        ObjectName: 'QuadPotbelly79',
        ClassName: 'Commander',
        DisplayName: 'Potbelly79',
        UnitSpec: '/pa/units/commanders/quad_potbelly79/quad_potbelly79.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_potbelly79.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_potbelly79.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_potbelly79_thumb.png',
        KSBacker: 'Sean Dougherty',
    },
    {
        ObjectName: 'ImperialTheChessKnight',
        ClassName: 'Commander',
        DisplayName: 'TheChessKnight',
        UnitSpec: '/pa/units/commanders/imperial_thechessknight/imperial_thechessknight.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_thechessknight.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_thechessknight.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_thechessknight_thumb.png',
    },
    {
        ObjectName: 'RaptorZaazzaa',
        ClassName: 'Commander',
        DisplayName: 'Zaazzaa',
        UnitSpec: '/pa/units/commanders/raptor_zaazzaa/raptor_zaazzaa.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_raptor_zaazzaa.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_raptor_zaazzaa.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_raptor_zaazzaa_thumb.png',
    },
    {
        ObjectName: 'QuadTokamaktech',
        ClassName: 'Commander',
        DisplayName: 'Tokamaktech',
        UnitSpec: '/pa/units/commanders/quad_tokamaktech/quad_tokamaktech.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_tokamaktech.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_tokamaktech.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_tokamaktech_thumb.png',
        KSBacker: 'Cdr Paul Geraghty',
    },
    {
        ObjectName: 'RaptorDiremachine',
        ClassName: 'Commander',
        DisplayName: 'Diremachine',
        UnitSpec: '/pa/units/commanders/raptor_diremachine/raptor_diremachine.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_raptor_diremachine.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_raptor_diremachine.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_raptor_diremachine_thumb.png',
        KSBacker: '',
    },
    {
        ObjectName: 'RaptorStickman9000',
        ClassName: 'Commander',
        DisplayName: 'Stickman9000',
        UnitSpec: '/pa/units/commanders/raptor_stickman9000/raptor_stickman9000.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_raptor_stickman9000.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_raptor_stickman9000.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_raptor_stickman9000_thumb.png',
        KSBacker: 'Kyle Gretchev',
    },
    {
        ObjectName: 'RaptorBeniesk',
        ClassName: 'Commander',
        DisplayName: 'Beniesk',
        UnitSpec: '/pa/units/commanders/raptor_beniesk/raptor_beniesk.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_raptor_beniesk.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_raptor_beniesk.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_raptor_beniesk_thumb.png',
    },
    {
        ObjectName: 'QuadMobiousblack',
        ClassName: 'Commander',
        DisplayName: 'Berlinetta',
        UnitSpec: '/pa/units/commanders/quad_mobiousblack/quad_mobiousblack.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_mobiousblack.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_mobiousblack.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_mobiousblack_thumb.png',
        KSBacker: 'B.A.S.',
    },
    {
        ObjectName: 'TankBanditks',
        ClassName: 'Commander',
        DisplayName: 'Banditks',
        UnitSpec: '/pa/units/commanders/tank_banditks/tank_banditks.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_tank_banditks.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_tank_banditks.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_tank_banditks_thumb.png',
        KSBacker: 'Matthew Hanna',
    },
    {
        ObjectName: 'QuadRaventhornn',
        ClassName: 'Commander',
        DisplayName: 'Raventhornn',
        UnitSpec: '/pa/units/commanders/quad_raventhornn/quad_raventhornn.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_raventhornn.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_raventhornn.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_raventhornn_thumb.png',
    },
    {
        ObjectName: 'ImperialFiveleafclover',
        ClassName: 'Commander',
        DisplayName: 'Fiveleafclover',
        UnitSpec: '/pa/units/commanders/imperial_fiveleafclover/imperial_fiveleafclover.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_fiveleafclover.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_fiveleafclover.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_fiveleafclover_thumb.png',
    },
    {
        ObjectName: 'ImperialSeniorhelix',
        ClassName: 'Commander',
        DisplayName: 'Seniorhelix',
        UnitSpec: '/pa/units/commanders/imperial_seniorhelix/imperial_seniorhelix.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_seniorhelix.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_seniorhelix.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_seniorhelix_thumb.png',
    },
    {
        ObjectName: 'ImperialEnzomatrix',
        ClassName: 'Commander',
        DisplayName: 'Enzomatrix',
        UnitSpec: '/pa/units/commanders/imperial_enzomatrix/imperial_enzomatrix.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_enzomatrix.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_enzomatrix.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_enzomatrix_thumb.png',
        KSBacker: 'Enzo.Matrix',
    },
    {
        ObjectName: 'RaptorMajuju',
        ClassName: 'Commander',
        DisplayName: 'Majuju',
        UnitSpec: '/pa/units/commanders/raptor_majuju/raptor_majuju.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_raptor_majuju.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_raptor_majuju.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_raptor_majuju_thumb.png',
    },
    {
        ObjectName: 'ImperialMjon',
        ClassName: 'Commander',
        DisplayName: 'Mjon',
        UnitSpec: '/pa/units/commanders/imperial_mjon/imperial_mjon.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_mjon.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_mjon.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_mjon_thumb.png',
    },
    {
        ObjectName: 'ImperialAceAl',
        ClassName: 'Commander',
        DisplayName: 'AceAl',
        UnitSpec: '/pa/units/commanders/imperial_aceal/imperial_aceal.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_aceal.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_aceal.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_aceal_thumb.png',
        KSBacker: '416365416c',
    },
    {
        ObjectName: 'ImperialToddFather',
        ClassName: 'Commander',
        DisplayName: 'ToddFather',
        UnitSpec: '/pa/units/commanders/imperial_toddfather/imperial_toddfather.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_toddfather.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_toddfather.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_toddfather_thumb.png',
        KSBacker: 'ToddFather',
    },
    {
        ObjectName: 'QuadTheFlax',
        ClassName: 'Commander',
        DisplayName: 'TheFlax',
        UnitSpec: '/pa/units/commanders/quad_theflax/quad_theflax.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_theflax.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_theflax.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_theflax_thumb.png',
        KSBacker: 'Felix "Flax" Le Rouzes',
    },
    {
        ObjectName: 'ImperialStelarch',
        ClassName: 'Commander',
        DisplayName: 'Stelarch',
        UnitSpec: '/pa/units/commanders/imperial_stelarch/imperial_stelarch.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_stelarch.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_stelarch.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_stelarch_thumb.png',
        KSBacker: 'Stelarch',
    },
    {
        ObjectName: 'QuadSpartandano',
        ClassName: 'Commander',
        DisplayName: 'Spartandano',
        UnitSpec: '/pa/units/commanders/quad_spartandano/quad_spartandano.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_spartandano.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_spartandano.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_spartandano_thumb.png',
        KSBacker: 'Dan Allen',
    },
    {
        ObjectName: 'todo1',
        ClassName: 'Commander',
        DisplayName: 'todo1',
        UnitSpec: '/pa/units/commanders/todo1/todo1.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_imperial_stelarch.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_imperial_stelarch.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_imperial_stelarch_thumb.png'
    },
    {
        ObjectName: 'todo2',
        ClassName: 'Commander',
        DisplayName: 'todo2',
        UnitSpec: '/pa/units/commanders/todo2/todo2.json',
        ImgSource: 'coui://ui/main/shared/img/commanders/img_quad_spartandano.png',
        ProfileImgSource: 'coui://ui/main/shared/img/commanders/profiles/profile_quad_spartandano.png',
        ThumbImgSource: 'coui://ui/main/shared/img/commanders/thumbs/img_quad_spartandano_thumb.png'
    },
    {
        ObjectName: 'AlphaBadge',
        ClassName: 'Badge',
        DisplayName: 'Alpha Participant',
        ImgSource: 'coui://ui/main/shared/img/badges/badge_alpha.png',
    },
    {
        ObjectName: 'BetaBadge',
        ClassName: 'Badge',
        DisplayName: 'Beta Participant',
        ImgSource: 'coui://ui/main/shared/img/badges/badge_beta.png'
    },
    {
        ObjectName: 'VIPBadge',
        ClassName: 'Badge',
        DisplayName: 'Uber VIP',
        ImgSource: 'coui://ui/main/shared/img/badges/badge_uber_vip.png'
    },
    {
        ObjectName: 'CustomComBadge',
        ClassName: 'Badge',
        DisplayName: 'Custom Commander Backer',
        ImgSource: 'coui://ui/main/shared/img/badges/badge_custom_commander.png'
    },
    {
        ObjectName: 'KickstarterBadge',
        ClassName: 'Badge',
        DisplayName: 'Kickstarter Backer',
        ImgSource: 'coui://ui/main/shared/img/badges/badge_kickstarter.png'
    },
    {
        ObjectName: 'CosmicBadge',
        ClassName: 'Badge',
        DisplayName: 'PA Founding Commander',
        ImgSource: 'coui://ui/main/shared/img/badges/badge_cosmic.png'
    },
    {
        ObjectName: 'PASoundtrack',
        DisplayName: 'Planetary Annihilation Original Soundtrack',
    },
];

